add parachain MultiLocation
paritytech/ethereum-xcm-v3 pull request #1
Opened 2023-03-27 14:05 UTC by lana-shanghai

2023-03-27 15:44 UTC, bidzyyys requested changes
Add `X1(AccountId32)`

2023-03-27 15:44 UTC, bidzyyys commented on src/MultiLocationEncoder.sol
> +    function encodeMultiLocationSameConsensusAccountId32(
IMHO it should be `X1(AccountId32)`:
```
Example: /AccountID32(0x234234)
```

2023-03-28 14:54 UTC, sbp-parity approved these changes
LGTM 👍

2023-03-28 14:57 UTC, bidzyyys approved these changes
LGTM 👍

2023-03-28 14:57 UTC, merged

2023-03-29 09:30 UTC, vgeddes reviewed
Looks great! Added a few minor comments.

2023-03-29 09:30 UTC, vgeddes commented on src/MultiLocationEncoder.sol
> +        return abi.encodePacked(
Should rather use [byte.concat](https://docs.soliditylang.org/en/v0.8.17/types.html#the-functions-bytes-concat-and-string-concat), which was introduced for this purpose. The former `abi.encodePacked` is [discouraged](https://github.com/ethereum/solidity/issues/10903) for concatenating bytes.

2023-03-29 09:30 UTC, vgeddes commented on src/XCMEnums.sol
> +}
needs newline 😄

2023-03-29 09:30 UTC, vgeddes commented on src/XCMEnums.sol
> +library XCMEnums {
This library is a bit unnecessary. Can define the enums at the toplevel like so:

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.19;

enum XcmV3Junction {
    Parachain,
    AccountId32,
    AccountIndex64,
    AccountKey20,
    PalletInstance,
    GeneralIndex,
    GeneralKey,
    OnlyChild,
    Plurality,
    GlobalConsensus
}

```

2023-03-29 09:30 UTC, vgeddes commented on src/utils/ScaleCodec.sol
> +}
missing newline

2023-03-29 09:30 UTC, vgeddes commented on src/MultiLocationEncoder.sol
> +    function encodeMultiLocationSameConsensusParachain(
Is a fairly verbose function name. Given that name of the contract suggests multilocation encoding, could condense the name to `encodeRelativeParachain`.